version: "3.8"
services:
  kafka1:
    image: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CLUSTER_ID: 123456789001
    volumes:
      - ./props/server.properties:/kafka/config/kraft/server.properties
      - ./data:/tmp/kafka-logs